name: Deploy to Pages

on:
  push:
    branches:    
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: cd app && npm install && ASSETS_PREFIX=/facial-recognition-app/ npm run export
    - name: Push to Pages
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'app/out'
        target-directory: 'facial-recognition-app'
        destination-github-username: 'Devalent'
        destination-repository-name: 'Devalent.github.io'
        user-email: info@devalent.com
        target-branch: main
